
package ru.mxmztsv.app;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientServiceImpl", targetNamespace = "http://app.mxmztsv.ru/")
@XmlSeeAlso({
    ru.mxmztsv.app.ObjectFactory.class,
    ru.mxmztsv.app.model.ObjectFactory.class
})
public interface ClientServiceImpl {


    /**
     * 
     * @param firstName
     * @param lastName
     * @param data
     * @param category
     * @param status
     * @return
     *     returns ru.mxmztsv.app.ClientSearchResponseType
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(name = "ClientSearchResponse", targetNamespace = "http://app.mxmztsv.ru/")
    @RequestWrapper(localName = "searchClients", targetNamespace = "http://app.mxmztsv.ru/", className = "ru.mxmztsv.app.SearchClients")
    @ResponseWrapper(localName = "searchClientsResponse", targetNamespace = "http://app.mxmztsv.ru/", className = "ru.mxmztsv.app.SearchClientsResponse")
    @Action(input = "http://app.mxmztsv.ru/ClientServiceImpl/searchClientsRequest", output = "http://app.mxmztsv.ru/ClientServiceImpl/searchClientsResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://app.mxmztsv.ru/ClientServiceImpl/searchClients/Fault/ParseException")
    })
    public ClientSearchResponseType searchClients(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "status", targetNamespace = "")
        Status status,
        @WebParam(name = "category", targetNamespace = "")
        Category category,
        @WebParam(name = "data", targetNamespace = "")
        String data)
        throws ParseException_Exception
    ;

}
